### PR TITLE
update godoc for schema

### PR DESCRIPTION
**Pull request by lavalamp**
Since the schema has drifted slightly from the document, try to document it (in godoc) very clearly.

### CODE REVIEW

**Comment by lavalamp** [comment]
"Iff" is a common abbreviation of if-and-only-if, at least in papers talking about boolean algebra or philosophy :) Also we can probably get you in the org so you can lgtm for real, I forget the process, you might already meet the requirements.

@apelisse would you like to lgtm for real?

**Comment by kwiesmueller** [comment]
Well, yeah...
My fault, wasn't expecting it in a comment so i thought about a typo, but makes sense.
Then :+1: 

About the reqs, I think one is to have supporters from 2 companies which I am not sure I have.

**Pull request merged**
