### PR TITLE
Add update code

### PR DESCRIPTION
**Pull request by apelisse**
Improve a few things in the test framework and add the code for the updater. This is still mostly missing tests, but the goal is that we can share that duty as soon as possible.

### CODE REVIEW

**Comment by lavalamp** [comment]
lgtm, can you maybe squash down e.g. the fixup commits (the last two at least)?

**Comment by apelisse** [comment]
> lgtm, can you maybe squash down e.g. the fixup commits (the last two at least)?

Sure!

**Comment by apelisse** [comment]
squashed the last two1

**Pull request merged**
