### PR TITLE
Fix panic on pointer to embedded struct

### PR DESCRIPTION
**Pull request by christarazi**
This PR converts an embedded struct into its original type if it is
a pointer.

Fixes: https://github.com/kubernetes-sigs/structured-merge-diff/issues/172

### CODE REVIEW

**Comment by jpbetz** [comment]
The fix looks right to me. Would you add a test to ensure this doesn't get broken in the future? It should be as simple as adding a new tests struct and case here: https://github.com/kubernetes-sigs/structured-merge-diff/blob/1cc6019316282e0491aa45d2880b33c802848cf1/value/valuereflect_test.go#L241

**Comment by timebertt** [comment]
@christarazi what's the status on this?
We have also hit this issue (ref https://github.com/gardener/gardener/issues/2977) and would be very interested in having a upstream fix.

**Comment by christarazi** [comment]
@timebertt Apologies, yes this is still on my radar. Just trying to find the time :). Hopefully in the next week or so.

**Comment by christarazi** [comment]
I signed it

**Comment by christarazi** [comment]
I signed it

**Comment by apelisse** [comment]
ping @jpbetz

**Comment by ialidzhikov** [comment]
/kind bug
/priority important-soon

@jpbetz, could you please recheck?

**Pull request merged**
