### PR TITLE
Update dependecy to version where they solve a security vulnerability

### PR DESCRIPTION
**Pull request by Limoncho-san**
Need in order to solve white source security vulnerability

### CODE REVIEW

**Comment by Limoncho-san** [comment]
I signed it

**Comment by Limoncho-san** [comment]
This pr is regarding https://github.com/kubernetes-sigs/structured-merge-diff/issues/196 this issue

**Comment by Jefftree** [comment]
Please follow the instructions in the failing test to update the `go.sum` as well. Thanks!

**Comment by lavalamp** [comment]
I think running `go mod tidy` will probably fix it up.

**Pull request closed without merging**
