### PR TITLE
Fix exponential merge recursion

### PR DESCRIPTION
**Pull request by alexzielenski**
fixes an exponential recursion bug reproduced by the introduced benchmark 

occurs when attempting to merge `__untyped_deduced_` map with a nil value `lhs` and non-nil `rhs`. `deduceAtom` will just return the same input, so merge will create a new branch for recursion. Every nested level of fields ends up exponentially creating more merge branches. This PR adds logic so that the extra nil subtree is not traversed needlessly, and only the other operand's type is used for traversal.

### CODE REVIEW

**Comment by apelisse** [comment]
Looks good to me, that's really awesome. We can't really show the performance improvement since the benchmark doesn't finish in the main branch.

**Comment by apelisse** [comment]
Thanks,
/lgtm
@lavalamp, do you want to have a look? I'll approve if needed.

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
