### PR TITLE
implement BST for merging

### PR DESCRIPTION
**Pull request by jiahuif**

### CODE REVIEW

**Comment by apelisse** [comment]
Did you run the benchmarks? Maybe I made a mistake but it's not great so far:
```
> benchstat master.bench 207.bench 
name                                                 old time/op    new time/op    delta
Operations/Pod/Create-8                                72.6µs ± 0%   201.6µs ± 2%  +177.84%  (p=0.000 n=6+10)
Operations/Pod/Apply-8                                  182µs ± 1%     454µs ± 9%  +149.70%  (p=0.000 n=8+10)
Operations/Pod/ApplyTwice-8                             423µs ± 1%     963µs ± 1%  +127.62%  (p=0.000 n=10+8)
Operations/Pod/Update-8                                 190µs ± 3%     451µs ± 1%  +137.71%  (p=0.000 n=9+10)
Operations/Pod/UpdateVersion-8                          266µs ± 2%     674µs ± 4%  +152.96%  (p=0.000 n=8+10)
Operations/Node/Create-8                                123µs ± 9%     166µs ± 7%   +35.27%  (p=0.000 n=10+10)
Operations/Node/Apply-8                                 283µs ± 8%     371µs ± 1%   +31.02%  (p=0.000 n=10+10)
Operations/Node/ApplyTwice-8                            673µs ±15%     849µs ± 1%   +26.17%  (p=0.000 n=10+10)
Operations/Node/Update-8                                280µs ± 4%     380µs ± 1%   +35.76%  (p=0.000 n=10+9)
Operations/Node/UpdateVersion-8                         407µs ± 2%     560µs ± 1%   +37.75%  (p=0.000 n=9+9)
Operations/Endpoints/Create-8                          7.75µs ± 3%    7.94µs ± 1%    +2.42%  (p=0.007 n=10+9)
Operations/Endpoints/Apply-8                           16.5µs ± 1%    17.0µs ± 4%    +3.11%  (p=0.000 n=9+10)
Operations/Endpoints/ApplyTwice-8                      1.14ms ± 2%    1.17ms ± 3%    +2.77%  (p=0.003 n=10+9)
Operations/Endpoints/Update-8                          1.11ms ± 1%    1.21ms ±10%    +9.52%  (p=0.000 n=9+10)
Operations/Endpoints/UpdateVersion-8                   2.24ms ± 4%    2.29ms ± 4%      ~     (p=0.063 n=10+10)
Operations/CustomResourceDefinition/Create-8            767µs ± 1%     783µs ± 1%    +2.09%  (p=0.000 n=9+10)
Operations/CustomResourceDefinition/Apply-8            1.84ms ± 2%    1.89ms ± 2%    +2.91%  (p=0.000 n=10+9)
Operations/CustomResourceDefinition/ApplyTwice-8       4.02ms ± 3%    4.08ms ± 1%    +1.57%  (p=0.043 n=10+8)
Operations/CustomResourceDefinition/Update-8           1.83ms ± 8%    1.83ms ± 4%      ~     (p=0.481 n=10+10)
Operations/CustomResourceDefinition/UpdateVersion-8    2.65ms ± 5%    2.68ms ± 4%      ~     (p=0.666 n=9+9)

name                                                 old alloc/op   new alloc/op   delta
Operations/Pod/Create-8                                21.1kB ± 0%    89.4kB ± 0%  +324.80%  (p=0.000 n=10+10)
Operations/Pod/Apply-8                                 52.4kB ± 0%   189.3kB ± 0%  +261.16%  (p=0.000 n=10+10)
Operations/Pod/ApplyTwice-8                             106kB ± 0%     381kB ± 0%  +260.89%  (p=0.000 n=10+10)
Operations/Pod/Update-8                                39.4kB ± 0%   177.2kB ± 0%  +349.91%  (p=0.000 n=10+10)
Operations/Pod/UpdateVersion-8                         51.6kB ± 0%   258.8kB ± 0%  +401.13%  (p=0.000 n=8+9)
Operations/Node/Create-8                               30.0kB ± 0%    55.4kB ± 0%   +84.78%  (p=0.000 n=10+10)
Operations/Node/Apply-8                                73.4kB ± 0%   124.3kB ± 0%   +69.20%  (p=0.000 n=10+10)
Operations/Node/ApplyTwice-8                            152kB ± 0%     257kB ± 0%   +69.31%  (p=0.000 n=10+9)
Operations/Node/Update-8                               60.3kB ± 0%   112.8kB ± 0%   +87.23%  (p=0.000 n=9+9)
Operations/Node/UpdateVersion-8                        81.8kB ± 0%   161.5kB ± 0%   +97.39%  (p=0.000 n=10+10)
Operations/Endpoints/Create-8                          3.59kB ± 0%    3.59kB ± 0%      ~     (all equal)
Operations/Endpoints/Apply-8                           6.39kB ± 0%    6.39kB ± 0%      ~     (p=1.000 n=10+10)
Operations/Endpoints/ApplyTwice-8                       126kB ± 0%     126kB ± 0%      ~     (p=1.000 n=10+10)
Operations/Endpoints/Update-8                           119kB ± 0%     119kB ± 0%      ~     (p=0.761 n=10+9)
Operations/Endpoints/UpdateVersion-8                    233kB ± 0%     233kB ± 0%      ~     (p=0.670 n=10+10)
Operations/CustomResourceDefinition/Create-8            170kB ± 0%     170kB ± 0%      ~     (p=0.813 n=10+10)
Operations/CustomResourceDefinition/Apply-8             482kB ± 0%     482kB ± 0%      ~     (p=0.912 n=10+10)
Operations/CustomResourceDefinition/ApplyTwice-8        959kB ± 0%     959kB ± 0%      ~     (p=0.063 n=10+10)
Operations/CustomResourceDefinition/Update-8            335kB ± 0%     335kB ± 0%      ~     (p=0.644 n=10+10)
Operations/CustomResourceDefinition/UpdateVersion-8     454kB ± 0%     454kB ± 0%      ~     (p=0.247 n=10+10)

name                                                 old allocs/op  new allocs/op  delta
Operations/Pod/Create-8                                   474 ± 0%       588 ± 0%   +24.05%  (p=0.000 n=10+10)
Operations/Pod/Apply-8                                  1.25k ± 0%     1.48k ± 0%   +18.34%  (p=0.000 n=10+10)
Operations/Pod/ApplyTwice-8                             2.61k ± 0%     3.11k ± 0%   +19.18%  (p=0.000 n=9+10)
Operations/Pod/Update-8                                   972 ± 0%      1222 ± 0%   +25.75%  (p=0.000 n=10+10)
Operations/Pod/UpdateVersion-8                          1.40k ± 0%     1.78k ± 0%   +27.59%  (p=0.000 n=10+10)
Operations/Node/Create-8                                  558 ± 0%       650 ± 0%   +16.49%  (p=0.000 n=10+10)
Operations/Node/Apply-8                                 1.56k ± 0%     1.75k ± 0%   +11.86%  (p=0.000 n=10+10)
Operations/Node/ApplyTwice-8                            3.51k ± 0%     3.93k ± 0%   +11.88%  (p=0.000 n=8+10)
Operations/Node/Update-8                                1.41k ± 0%     1.62k ± 0%   +14.83%  (p=0.000 n=10+9)
Operations/Node/UpdateVersion-8                         2.16k ± 0%     2.49k ± 0%   +15.02%  (p=0.000 n=10+10)
Operations/Endpoints/Create-8                            77.0 ± 0%      77.0 ± 0%      ~     (all equal)
Operations/Endpoints/Apply-8                              148 ± 0%       148 ± 0%      ~     (all equal)
Operations/Endpoints/ApplyTwice-8                       6.33k ± 0%     6.33k ± 0%      ~     (all equal)
Operations/Endpoints/Update-8                           6.18k ± 0%     6.18k ± 0%      ~     (all equal)
Operations/Endpoints/UpdateVersion-8                    12.2k ± 0%     12.2k ± 0%      ~     (all equal)
Operations/CustomResourceDefinition/Create-8            3.71k ± 0%     3.71k ± 0%      ~     (all equal)
Operations/CustomResourceDefinition/Apply-8             10.3k ± 0%     10.3k ± 0%      ~     (p=0.714 n=10+10)
Operations/CustomResourceDefinition/ApplyTwice-8        21.3k ± 0%     21.3k ± 0%      ~     (p=0.055 n=10+10)
Operations/CustomResourceDefinition/Update-8            8.26k ± 0%     8.26k ± 0%      ~     (all equal)
Operations/CustomResourceDefinition/UpdateVersion-8     12.7k ± 0%     12.7k ± 0%      ~     (p=0.465 n=10+10)
```

**Comment by apelisse** [comment]
@jiahuif do we want to continue with that? Or should we close.

**Comment by jiahuif** [comment]
Let's close that. I can rethink about this. Now that we have generic in go 1.18, we can unify these data structures once and for all. I will need to rework on that using generic.

**Pull request closed without merging**
