### PR TITLE
[Trival] replace beta label to GA label for kubernetes

### PR DESCRIPTION
**Pull request by wawa0210**
/kind cleanup

Ref: kubernetes/kubernetes#89477

### CODE REVIEW

**Comment by apelisse** [comment]
Looks like you haven't updated properly? The test is failing.

Thanks!

**Comment by wawa0210** [comment]
> Looks like you haven't updated properly? The test is failing.
> 
> Thanks!

Done ~
Sorry, the test code was not modified before

**Comment by wawa0210** [comment]
@apelisse Can you take the time to review it again?

**Comment by apelisse** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
