### PR TITLE
Oneof lists

### PR DESCRIPTION
**Pull request by apelisse**
Implement support for multiple oneof's in the same structure.

/assign @jennybuckley 
/cc @lavalamp

### CODE REVIEW

**Comment by jennybuckley** [comment]
This looks good, do we need anything validating that there is no overlap within the unions? or will that be in a different layer

**Comment by apelisse** [comment]
Yeah, I was thinking about that, I'll add this here.

**Comment by apelisse** [comment]
Actually it should happen in `openapi -> smd`.

**Pull request merged**
