### PR TITLE
Update everything to v2

### PR DESCRIPTION
**Pull request by apelisse**
Backward compatibility has definitely changed, so I think it's time that we make it v2.

### CODE REVIEW

**Comment by jpbetz** [comment]
The mechanical change looks good.

Are we setting precedence for using v2 go modules in k8s? Or has the been done before for any of the other sub-projects? I haven't had the time to think through how version tags would work, any thing we can reference or add to this PR about that might be valuable.

**Comment by apelisse** [comment]
This follows the recommandation from: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by liggitt** [comment]
The go.mod file module name needs /v2 appended. The fact that tests passed without that is concerning as well… it means the code in this PR isn't what CI is testing.

**Comment by apelisse** [comment]
Wait, it has the name appended, I'm not sure what you're talking about ...

**Comment by liggitt** [comment]
Weird, I totally missed that somehow.

**Comment by liggitt** [comment]
Agree the mechanics look fine. I'm not quite sure when we would want to add v2.x.y tags. We may want to tag this commit with v2.0.0-alpha.0 or something similar so the first commit with a v2 go.mod has a v2 tag.

**Comment by liggitt** [comment]
Separately, it would also be good to document / formalize how we determined go API compatibility had been broken and a major revision was required. An automated test that uses [apidiff](https://github.com/golang/exp/blob/master/cmd/apidiff/main.go) to record the public API of the last tagged release in a file, and a CI job that flags breakages against it would be really useful in avoiding accidental API breakages.

**Comment by apelisse** [comment]
Absolutely a great idea!

With regard to tagging, we can't tag until the commit is merged, would you mind approving?

**Comment by apelisse** [comment]
Thanks!

**Pull request merged**
