### PR TITLE
WIP: Add example of testing compatibility change

### PR DESCRIPTION
**Pull request by apelisse**
This creates an example of a compatibility test. It's not great, but we get it mostly for free.

In this case it would show that going from atomic to associative (and vice-versa) is bad because we wouldn't be able to "resolve" the managed fields from one to the other. Even though, maybe we can fix the code to do the right thing.

I'm still not completely convinced that this test does the right thing so I have to think a little bit about it.

cc @mariantalla @lavalamp @jennybuckley

### CODE REVIEW

**Comment by apelisse** [comment]
I suspect we could split this PR in two, the part that adds the feature, and the part that has the test. The test is no good but the feature should be doing the right thing.

**Comment by jennybuckley** [comment]
in `broken_atomic_doesnt_own_former_associative` I would expect that "one" would not manage anything, and that "other" would only manage ".list"
in `broken_associative_doesnt_own_former_atomic` I think I would expect that "one" would not manage anything, and "other" would manage {".list[b]", ".list[b].name", ".list[b].value"}
So these tests do seem to do something unexpected.

**Comment by jennybuckley** [comment]
I think the issue is that it's using "associativeListParser" instead of "atomicListParser" actually

**Comment by apelisse** [comment]
Yeah, the test is clearly broken in many ways. Thanks for looking at it Jenny. We clearly need more tests like this though.

**Pull request closed without merging**
